#src/Assignment1/BookReviewBundle/Resources/config/routing.yml
book_review_index:
    path:     /
    defaults: { _controller: BookReviewBundle:Page:index }

book_review_about:
    path:     /about/
    defaults: { _controller: BookReviewBundle:Page:about}

book_review_add_book:
    path:     /books/new/{authorId}
    defaults: { _controller: BookReviewBundle:Book:new}
    requirements:
        id: \d+

book_review_edit_book:
    path:     /books/edit/{bookId}
    defaults: { _controller: BookReviewBundle:Book:edit}
    requirements:
        id: \d+

book_review_view_book:
    path:     /books/{bookId}
    defaults: { _controller: BookReviewBundle:Book:view }
    requirements:
        id: \d+

book_review_view_user:
    path:     /users/{userId}
    defaults: { _controller: BookReviewBundle:Page:user }
    requirements:
        id: \d+

book_review_add_author:
    path:     /authors/new
    defaults: { _controller: BookReviewBundle:Author:new}

book_review_edit_author:
    path:     /authors/edit/{authorId}
    defaults: { _controller: BookReviewBundle:Author:edit}
    requirements:
        id: \d+

book_review_view_author:
    path:     /authors/{authorId}
    defaults: { _controller: BookReviewBundle:Author:view}
    requirements:
        id: \d+

book_review_edit_review:
    path:     /reviews/edit/{reviewId}
    defaults: { _controller: BookReviewBundle:Review:edit}
    requirements:
        id: \d+

book_review_delete_comment:
    path:     /reviews/deletecomment/{commentId}
    defaults: { _controller: BookReviewBundle:Review:deleteComment}
    requirements:
        id: \d+


book_review_view_review:
    path:     /reviews/{reviewId}
    defaults: { _controller: BookReviewBundle:Review:view}
    requirements:
        id: \d+

book_review_search:
    path:     /search/
    defaults: { _controller: BookReviewBundle:Search:view}

book_review_delete:
    path:     /delete/{entity}/{id}
    defaults: { _controller: BookReviewBundle:Delete:delete}




