<?php

namespace Assignment1\BookReviewBundle\Repository;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends \Doctrine\ORM\EntityRepository
{
}
